spring.application.name=Bus Management System
spring.datasource.url=jdbc:postgresql://localhost:5432/BusManagementDB
spring.datasource.username=postgres
spring.datasource.password=Saliim47

# Suppress static resource warnings
spring.web.resources.add-mappings=false


# Hibernate settings (optional but common)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true